language: haskell

ghc:
    - 7.4
    - 7.6
    - 7.8

before_install:
    - git clone https://github.com/augustss/geniplate.git

install:
    - cabal install bnfc geniplate/ 'mtl < 2.2' # or set transformers bound

before_script:
    - true

script:
    - (cd tip-lib/src && bnfc -m -p Parser TIP.bnfc && make)
    - cabal install tip-lib/ tip-haskell-frontend/
